services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modrinth
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: modrinth
    ports:
      - "8085:8080"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    environment:
      API_URL: https://mr-rev.realrobotix.me/api/
    ports:
      - "8086:80"

volumes:
  postgres_data:
