services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modrinth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d modrinth"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: modrinth
    ports:
      - "8083:8080"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    environment:
      API_URL: https://mr-rev.realrobotix.me/api/
    ports:
      - "8086:80"

volumes:
  postgres_data:
